"""change text to reviews text in reviews table

Revision ID: 3ef891aa8f68
Revises: ed9a7f2a0d20
Create Date: 2023-12-18 05:32:33.496372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef891aa8f68'
down_revision: Union[str, None] = 'ed9a7f2a0d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviews_text', sa.Text(), nullable=False))
    op.drop_column('reviews', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'reviews_text')
    # ### end Alembic commands ###
